version: "3.8"
services:
  filebrowser:
    container_name: filebrowser-quantum
    image: gtstef/filebrowser:1.5.1-stable # https://github.com/gtsteffaniak/filebrowser/pkgs/container/filebrowser
    volumes:
      - /volume1:/volume1 # Do not use a root "/" directory or include the "/var" folder
      - /volume2:/volume2
      - /volume2/dockerssd/filebrowser-quantum/data:/home/filebrowser/data
    ports:
      - 8147:80 # exposes port 80 to host, the left-side number can be changed without config.yaml changes.
    restart: unless-stopped
